//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMSExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutBox_AboutBox_About0 {
            get {
                return ResourceManager.GetString("AboutBox_AboutBox_About0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AMSLogin_buttonExport_Click_Error {
            get {
                return ResourceManager.GetString("AMSLogin_buttonExport_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import and replace.
        /// </summary>
        internal static string AMSLogin_buttonImportAll_Click_ImportAndReplace {
            get {
                return ResourceManager.GetString("AMSLogin_buttonImportAll_Click_ImportAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are current entries in the list.
        ///Do you want replace them with the new ones or do a merge?
        ///
        ///Select &apos;Yes&apos; to replace them, &apos;No&apos; to merge them..
        /// </summary>
        internal static string AMSLogin_buttonImportAll_Click_ThereAreCurrentEntriesInTheListNDoYouWantReplaceThemWithTheNewOnesOrDoAMergeNNSelectYesToReplaceThemNoToMergeThem {
            get {
                return ResourceManager.GetString("AMSLogin_buttonImportAll_Click_ThereAreCurrentEntriesInTheListNDoYouWantReplaceTh" +
                        "emWithTheNewOnesOrDoAMergeNNSelectYesToReplaceThemNoToMergeThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is mandatory.
        /// </summary>
        internal static string AMSLogin_CheckTextBox_ThisFieldIsMandatory {
            get {
                return ResourceManager.GetString("AMSLogin_CheckTextBox_ThisFieldIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}, {2}).
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_012ScaleUnit {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_012ScaleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}, {2}) Custom hostname : {3}.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_012ScaleUnitCustomHostname3 {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_012ScaleUnitCustomHostname3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_Created {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_LastModified {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_Name {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_State {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_Type {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date time: {0}.
        /// </summary>
        internal static string AssetInformation_BuildLocatorsTree_ExpirationDateTime0 {
            get {
                return ResourceManager.GetString("AssetInformation_BuildLocatorsTree_ExpirationDateTime0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locator information.
        /// </summary>
        internal static string AssetInformation_BuildLocatorsTree_LocatorInformation {
            get {
                return ResourceManager.GetString("AssetInformation_BuildLocatorsTree_LocatorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string AssetInformation_BuildLocatorsTree_Name0 {
            get {
                return ResourceManager.GetString("AssetInformation_BuildLocatorsTree_Name0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time: {0}.
        /// </summary>
        internal static string AssetInformation_BuildLocatorsTree_StartTime0 {
            get {
                return ResourceManager.GetString("AssetInformation_BuildLocatorsTree_StartTime0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when creating the temporary SAS locator to the metadata file..
        /// </summary>
        internal static string AssetInformation_buttonAudioVideoAnalysis_Click_ErrorWhenCreatingTheTemporarySASLocatorToTheMetadataFile {
            get {
                return ResourceManager.GetString("AssetInformation_buttonAudioVideoAnalysis_Click_ErrorWhenCreatingTheTemporarySASL" +
                        "ocatorToTheMetadataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVR.
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_DVR {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_DVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVR (d.h:m:s).
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_DVRDHMS {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_DVRDHMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_End {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End (d.h:m:s).
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_EndDHMS {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_EndDHMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveBackoff.
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_LiveBackoff {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_LiveBackoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live backoff (d.h:m:s).
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_LiveBackoffDHMS {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_LiveBackoffDHMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_Rules {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_Start {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start (d.h:m:s).
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_StartDHMS {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_StartDHMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Rules.
        /// </summary>
        internal static string AssetInformation_DisplayAssetFilters_TrackRules {
            get {
                return ResourceManager.GetString("AssetInformation_DisplayAssetFilters_TrackRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset filter &apos;{0}&apos; has been created..
        /// </summary>
        internal static string AssetInformation_DoCreateAssetFilter_AssetFilter0HasBeenCreated {
            get {
                return ResourceManager.GetString("AssetInformation_DoCreateAssetFilter_AssetFilter0HasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when creating asset filter..
        /// </summary>
        internal static string AssetInformation_DoCreateAssetFilter_ErrorWhenCreatingAssetFilter {
            get {
                return ResourceManager.GetString("AssetInformation_DoCreateAssetFilter_ErrorWhenCreatingAssetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when creating asset filter &apos;{0}&apos;..
        /// </summary>
        internal static string AssetInformation_DoCreateAssetFilter_ErrorWhenCreatingAssetFilter0 {
            get {
                return ResourceManager.GetString("AssetInformation_DoCreateAssetFilter_ErrorWhenCreatingAssetFilter0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown name.
        /// </summary>
        internal static string AssetInformation_DoCreateAssetFilter_UnknownName {
            get {
                return ResourceManager.GetString("AssetInformation_DoCreateAssetFilter_UnknownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when deleting the files.
        /// </summary>
        internal static string AssetInformation_DoDeleteAllFiles_ErrorWhenDeletingTheFiles {
            get {
                return ResourceManager.GetString("AssetInformation_DoDeleteAllFiles_ErrorWhenDeletingTheFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when deleting asset filter(s)..
        /// </summary>
        internal static string AssetInformation_DoDeleteAssetFilter_ErrorWhenDeletingAssetFilterS {
            get {
                return ResourceManager.GetString("AssetInformation_DoDeleteAssetFilter_ErrorWhenDeletingAssetFilterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the file &apos;{0}&apos; ?.
        /// </summary>
        internal static string AssetInformation_DoDeleteFiles_DeleteTheFile0 {
            get {
                return ResourceManager.GetString("AssetInformation_DoDeleteFiles_DeleteTheFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete these {0} files ?.
        /// </summary>
        internal static string AssetInformation_DoDeleteFiles_DeleteThese0Files {
            get {
                return ResourceManager.GetString("AssetInformation_DoDeleteFiles_DeleteThese0Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when deleting file(s).
        /// </summary>
        internal static string AssetInformation_DoDeleteFiles_ErrorWhenDeletingFileS {
            get {
                return ResourceManager.GetString("AssetInformation_DoDeleteFiles_ErrorWhenDeletingFileS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deletion.
        /// </summary>
        internal static string AssetInformation_DoDeleteFiles_FileDeletion {
            get {
                return ResourceManager.GetString("AssetInformation_DoDeleteFiles_FileDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this locator ?.
        /// </summary>
        internal static string AssetInformation_DoDelLocator_AreYouSureThatYouWantToDeleteThisLocator {
            get {
                return ResourceManager.GetString("AssetInformation_DoDelLocator_AreYouSureThatYouWantToDeleteThisLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to delete the locator..
        /// </summary>
        internal static string AssetInformation_DoDelLocator_ErrorWhenTryingToDeleteTheLocator {
            get {
                return ResourceManager.GetString("AssetInformation_DoDelLocator_ErrorWhenTryingToDeleteTheLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locator deletion.
        /// </summary>
        internal static string AssetInformation_DoDelLocator_LocatorDeletion {
            get {
                return ResourceManager.GetString("AssetInformation_DoDelLocator_LocatorDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset report.
        /// </summary>
        internal static string AssetInformation_DoDisplayAssetStats_AssetReport {
            get {
                return ResourceManager.GetString("AssetInformation_DoDisplayAssetStats_AssetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See value.
        /// </summary>
        internal static string AssetInformation_DoDisplayAuthorizationPolicyOption_SeeValue {
            get {
                return ResourceManager.GetString("AssetInformation_DoDisplayAuthorizationPolicyOption_SeeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        internal static string AssetInformation_DoDisplayFileProperties_FileSize {
            get {
                return ResourceManager.GetString("AssetInformation_DoDisplayFileProperties_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        internal static string AssetInformation_DoDisplayFileProperties_LastModified {
            get {
                return ResourceManager.GetString("AssetInformation_DoDisplayFileProperties_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Key Value.
        /// </summary>
        internal static string AssetInformation_DoDisplayKeyPropertiesAndAutOptions_ClearKeyValue {
            get {
                return ResourceManager.GetString("AssetInformation_DoDisplayKeyPropertiesAndAutOptions_ClearKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see clear key.
        /// </summary>
        internal static string AssetInformation_DoDisplayKeyPropertiesAndAutOptions_SeeClearKey {
            get {
                return ResourceManager.GetString("AssetInformation_DoDisplayKeyPropertiesAndAutOptions_SeeClearKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See clear key.
        /// </summary>
        internal static string AssetInformation_DoDisplayKeyPropertiesAndAutOptions_SeeClearKey2 {
            get {
                return ResourceManager.GetString("AssetInformation_DoDisplayKeyPropertiesAndAutOptions_SeeClearKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download process has been initiated. See the Transfers tab to check the progress..
        /// </summary>
        internal static string AssetInformation_DoDownloadFiles_DownloadProcessHasBeenInitiatedSeeTheTransfersTabToCheckTheProgress {
            get {
                return ResourceManager.GetString("AssetInformation_DoDownloadFiles_DownloadProcessHasBeenInitiatedSeeTheTransfersTa" +
                        "bToCheckTheProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when deleting files.
        /// </summary>
        internal static string AssetInformation_DoDownloadFiles_ErrorWhenDeletingFiles {
            get {
                return ResourceManager.GetString("AssetInformation_DoDownloadFiles_ErrorWhenDeletingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when downloading file(s).
        /// </summary>
        internal static string AssetInformation_DoDownloadFiles_ErrorWhenDownloadingFileS {
            get {
                return ResourceManager.GetString("AssetInformation_DoDownloadFiles_ErrorWhenDownloadingFileS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) overwrite.
        /// </summary>
        internal static string AssetInformation_DoDownloadFiles_FileSOverwrite {
            get {
                return ResourceManager.GetString("AssetInformation_DoDownloadFiles_FileSOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file is already in the folder
        ///
        ///{0}
        ///
        ///Overwite the file ?.
        /// </summary>
        internal static string AssetInformation_DoDownloadFiles_TheFollowingFileIsAlreadyInTheFolderNN0NNOverwiteTheFile {
            get {
                return ResourceManager.GetString("AssetInformation_DoDownloadFiles_TheFollowingFileIsAlreadyInTheFolderNN0NNOverwit" +
                        "eTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files are already in the folder(s)
        ///
        ///{0}
        ///
        ///Overwite the files ?.
        /// </summary>
        internal static string AssetInformation_DoDownloadFiles_TheFollowingFilesAreAlreadyInTheFolderSNN0NNOverwiteTheFiles {
            get {
                return ResourceManager.GetString("AssetInformation_DoDownloadFiles_TheFollowingFilesAreAlreadyInTheFolderSNN0NNOver" +
                        "witeTheFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of {0}.
        /// </summary>
        internal static string AssetInformation_DoDuplicate_CopyOf0 {
            get {
                return ResourceManager.GetString("AssetInformation_DoDuplicate_CopyOf0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the new duplicate file:.
        /// </summary>
        internal static string AssetInformation_DoDuplicate_EnterTheNameOfTheNewDuplicateFile {
            get {
                return ResourceManager.GetString("AssetInformation_DoDuplicate_EnterTheNameOfTheNewDuplicateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when duplicating this file.
        /// </summary>
        internal static string AssetInformation_DoDuplicate_ErrorWhenDuplicatingThisFile {
            get {
                return ResourceManager.GetString("AssetInformation_DoDuplicate_ErrorWhenDuplicatingThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        internal static string AssetInformation_DoDuplicate_NewName {
            get {
                return ResourceManager.GetString("AssetInformation_DoDuplicate_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string AssetInformation_DoDuplicateFilter_Copy {
            get {
                return ResourceManager.GetString("AssetInformation_DoDuplicateFilter_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the new duplicate filter:.
        /// </summary>
        internal static string AssetInformation_DoDuplicateFilter_EnterTheNameOfTheNewDuplicateFilter {
            get {
                return ResourceManager.GetString("AssetInformation_DoDuplicateFilter_EnterTheNameOfTheNewDuplicateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when duplicating asset filter..
        /// </summary>
        internal static string AssetInformation_DoDuplicateFilter_ErrorWhenDuplicatingAssetFilter {
            get {
                return ResourceManager.GetString("AssetInformation_DoDuplicateFilter_ErrorWhenDuplicatingAssetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when accessing/editing asset file..
        /// </summary>
        internal static string AssetInformation_DoEditFile_ErrorWhenAccessingEditingAssetFile {
            get {
                return ResourceManager.GetString("AssetInformation_DoEditFile_ErrorWhenAccessingEditingAssetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is to large to edit it online..
        /// </summary>
        internal static string AssetInformation_DoEditFile_FileIsToLargeToEditItOnline {
            get {
                return ResourceManager.GetString("AssetInformation_DoEditFile_FileIsToLargeToEditItOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online edit of &apos;{0}&apos;.
        /// </summary>
        internal static string AssetInformation_DoEditFile_OnlineEditOf0 {
            get {
                return ResourceManager.GetString("AssetInformation_DoEditFile_OnlineEditOf0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string AssetInformation_DoEditFile_Value {
            get {
                return ResourceManager.GetString("AssetInformation_DoEditFile_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset filter &apos;{0}&apos; has been updated..
        /// </summary>
        internal static string AssetInformation_DoFilterInfo_AssetFilter0HasBeenUpdated {
            get {
                return ResourceManager.GetString("AssetInformation_DoFilterInfo_AssetFilter0HasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when updating asset filter..
        /// </summary>
        internal static string AssetInformation_DoFilterInfo_ErrorWhenUpdatingAssetFilter {
            get {
                return ResourceManager.GetString("AssetInformation_DoFilterInfo_ErrorWhenUpdatingAssetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when updating asset filter &apos;{0}&apos;..
        /// </summary>
        internal static string AssetInformation_DoFilterInfo_ErrorWhenUpdatingAssetFilter0 {
            get {
                return ResourceManager.GetString("AssetInformation_DoFilterInfo_ErrorWhenUpdatingAssetFilter0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check carefully the content of the generated manifest as the tool makes guesses !.
        /// </summary>
        internal static string AssetInformation_DoGenerateManifest_PleaseCheckCarefullyTheContentOfTheGeneratedManifestAsTheToolMakesGuesses {
            get {
                return ResourceManager.GetString("AssetInformation_DoGenerateManifest_PleaseCheckCarefullyTheContentOfTheGeneratedM" +
                        "anifestAsTheToolMakesGuesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when accessing temporary SAS locator.
        /// </summary>
        internal static string AssetInformation_DoOpenFiles_ErrorWhenAccessingTemporarySASLocator {
            get {
                return ResourceManager.GetString("AssetInformation_DoOpenFiles_ErrorWhenAccessingTemporarySASLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no metadata for this file..
        /// </summary>
        internal static string AssetInformation_ShowFileMetadata_ThereIsNoMetadataForThisFile {
            get {
                return ResourceManager.GetString("AssetInformation_ShowFileMetadata_ThereIsNoMetadataForThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string BatchUploadFrame1_buttonNext_Click_Folder {
            get {
                return ResourceManager.GetString("BatchUploadFrame1_buttonNext_Click_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist.
        /// </summary>
        internal static string BatchUploadFrame1_buttonNext_Click_FolderDoesNotExist {
            get {
                return ResourceManager.GetString("BatchUploadFrame1_buttonNext_Click_FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} file).
        /// </summary>
        internal static string BatchUploadFrame2_BatchUploadFrame2_01File {
            get {
                return ResourceManager.GetString("BatchUploadFrame2_BatchUploadFrame2_01File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} files).
        /// </summary>
        internal static string BatchUploadFrame2_BatchUploadFrame2_01Files {
            get {
                return ResourceManager.GetString("BatchUploadFrame2_BatchUploadFrame2_01Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when reading files or folders..
        /// </summary>
        internal static string BatchUploadFrame2_BatchUploadFrame2_ErrorWhenReadingFilesOrFolders {
            get {
                return ResourceManager.GetString("BatchUploadFrame2_BatchUploadFrame2_ErrorWhenReadingFilesOrFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow All.
        /// </summary>
        internal static string ChannelInformation_buttonAllowAllInputIP_Click_AllowAll {
            get {
                return ResourceManager.GetString("ChannelInformation_buttonAllowAllInputIP_Click_AllowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Input URL ({1}).
        /// </summary>
        internal static string ChannelInformation_ChannelInformation_Load_0InputURL1 {
            get {
                return ResourceManager.GetString("ChannelInformation_ChannelInformation_Load_0InputURL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Input URL ({1}, SSL).
        /// </summary>
        internal static string ChannelInformation_ChannelInformation_Load_0InputURL1SSL {
            get {
                return ResourceManager.GetString("ChannelInformation_ChannelInformation_Load_0InputURL1SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ChannelInformation_ChannelInformation_Load_Description {
            get {
                return ResourceManager.GetString("ChannelInformation_ChannelInformation_Load_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input protocol.
        /// </summary>
        internal static string ChannelInformation_ChannelInformation_Load_InputProtocol {
            get {
                return ResourceManager.GetString("ChannelInformation_ChannelInformation_Load_InputProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (multiple channels have been selected).
        /// </summary>
        internal static string ChannelInformation_ChannelInformation_Load_MultipleChannelsHaveBeenSelected {
            get {
                return ResourceManager.GetString("ChannelInformation_ChannelInformation_Load_MultipleChannelsHaveBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview URL ({0}).
        /// </summary>
        internal static string ChannelInformation_ChannelInformation_Load_PreviewURL0 {
            get {
                return ResourceManager.GetString("ChannelInformation_ChannelInformation_Load_PreviewURL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary .
        /// </summary>
        internal static string ChannelInformation_ChannelInformation_Load_Primary {
            get {
                return ResourceManager.GetString("ChannelInformation_ChannelInformation_Load_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary .
        /// </summary>
        internal static string ChannelInformation_ChannelInformation_Load_Secondary {
            get {
                return ResourceManager.GetString("ChannelInformation_ChannelInformation_Load_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid.
        /// </summary>
        internal static string ChannelInformation_checkKeyFrameValue_ValueIsNotValid {
            get {
                return ResourceManager.GetString("ChannelInformation_checkKeyFrameValue_ValueIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset filter : .
        /// </summary>
        internal static string ChooseStreamingEndpoint_ChooseStreamingEndpoint_Load_AssetFilter {
            get {
                return ResourceManager.GetString("ChooseStreamingEndpoint_ChooseStreamingEndpoint_Load_AssetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default browser.
        /// </summary>
        internal static string ChooseStreamingEndpoint_ChooseStreamingEndpoint_Load_DefaultBrowser {
            get {
                return ResourceManager.GetString("ChooseStreamingEndpoint_ChooseStreamingEndpoint_Load_DefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account filter : .
        /// </summary>
        internal static string ChooseStreamingEndpoint_ChooseStreamingEndpoint_Load_GlobalFilter {
            get {
                return ResourceManager.GetString("ChooseStreamingEndpoint_ChooseStreamingEndpoint_Load_GlobalFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel name is not valid.
        /// </summary>
        internal static string CreateLiveChannel_checkChannelName_ChannelNameIsNotValid {
            get {
                return ResourceManager.GetString("CreateLiveChannel_checkChannelName_ChannelNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect IP address.
        /// </summary>
        internal static string CreateLiveChannel_checkIPAddress_IncorrectIPAddress {
            get {
                return ResourceManager.GetString("CreateLiveChannel_checkIPAddress_IncorrectIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format.
        /// </summary>
        internal static string CreateLiveChannel_dataGridView_DataError_WrongFormat {
            get {
                return ResourceManager.GetString("CreateLiveChannel_dataGridView_DataError_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string CreateLiveChannel_inputIPAllow_Default {
            get {
                return ResourceManager.GetString("CreateLiveChannel_inputIPAllow_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update locator(s).
        /// </summary>
        internal static string CreateLocator_CreateLocator_UpdateLocatorS {
            get {
                return ResourceManager.GetString("CreateLocator_CreateLocator_UpdateLocatorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update locators.
        /// </summary>
        internal static string CreateLocator_CreateLocator_UpdateLocators2 {
            get {
                return ResourceManager.GetString("CreateLocator_CreateLocator_UpdateLocators2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program name is not valid.
        /// </summary>
        internal static string CreateProgram_checkProgramName_ProgramNameIsNotValid {
            get {
                return ResourceManager.GetString("CreateProgram_checkProgramName_ProgramNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming Endpoint name is not valid.
        /// </summary>
        internal static string CreateStreamingEndpoint_checkSEName_StreamingEndpointNameIsNotValid {
            get {
                return ResourceManager.GetString("CreateStreamingEndpoint_checkSEName_StreamingEndpointNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate required.
        /// </summary>
        internal static string DynamicEncryption_GetCertificateFromFile_CertificateRequired {
            get {
                return ResourceManager.GetString("DynamicEncryption_GetCertificateFromFile_CertificateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No private key.
        /// </summary>
        internal static string DynamicEncryption_GetCertificateFromFile_NoPrivateKey {
            get {
                return ResourceManager.GetString("DynamicEncryption_GetCertificateFromFile_NoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX files|*.pfx|All files|*.*.
        /// </summary>
        internal static string DynamicEncryption_GetCertificateFromFile_PFXFilesPfxAllFiles {
            get {
                return ResourceManager.GetString("DynamicEncryption_GetCertificateFromFile_PFXFilesPfxAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX Password.
        /// </summary>
        internal static string DynamicEncryption_GetCertificateFromFile_PFXPassword {
            get {
                return ResourceManager.GetString("DynamicEncryption_GetCertificateFromFile_PFXPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password for the PFX file :.
        /// </summary>
        internal static string DynamicEncryption_GetCertificateFromFile_PleaseEnterThePasswordForThePFXFile {
            get {
                return ResourceManager.GetString("DynamicEncryption_GetCertificateFromFile_PleaseEnterThePasswordForThePFXFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a certificate file (.PFX) that contains both public and private keys. Private key is needed to sign the JWT token. It is recommended to use the same certifcate that the one used during the setup of dynamic encryption for this asset..
        /// </summary>
        internal static string DynamicEncryption_GetCertificateFromFile_PleaseSelectACertificateFilePFXThatContainsBothPublicAndPrivateKeysPrivateKeyIsNeededToSignTheJWTTokenItIsRecommendedToUseTheSameCertifcateThatTheOneUsedDuringTheSetupOfDynamicEncryptionForThisAsset {
            get {
                return ResourceManager.GetString("DynamicEncryption_GetCertificateFromFile_PleaseSelectACertificateFilePFXThatConta" +
                        "insBothPublicAndPrivateKeysPrivateKeyIsNeededToSignTheJWTTokenItIsRecommendedToU" +
                        "seTheSameCertifcateThatTheOneUsedDuringTheSetupOfDynamicEncryptionForThisAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate does not contain a private key..
        /// </summary>
        internal static string DynamicEncryption_GetCertificateFromFile_TheCertificateDoesNotContainAPrivateKey {
            get {
                return ResourceManager.GetString("DynamicEncryption_GetCertificateFromFile_TheCertificateDoesNotContainAPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error when opening the certificate file.
        ///{0}.
        /// </summary>
        internal static string DynamicEncryption_GetCertificateFromFile_ThereIsAnErrorWhenOpeningTheCertificateFileN0 {
            get {
                return ResourceManager.GetString("DynamicEncryption_GetCertificateFromFile_ThereIsAnErrorWhenOpeningTheCertificateF" +
                        "ileN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be higher than start time.
        /// </summary>
        internal static string DynManifestFilter_CheckIfErrorTimeControls_EndTimeMustBeHigherThanStartTime {
            get {
                return ResourceManager.GetString("DynManifestFilter_CheckIfErrorTimeControls_EndTimeMustBeHigherThanStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not recommended to use an Account Filter to do time trimming. Consider creating an asset filter instead..
        /// </summary>
        internal static string DynManifestFilter_CheckIfErrorTimeControls_ItIsNotRecommendedToUseAGlobalFilterToDoTimeTrimmingConsiderCreatingAnAssetFilterInstead {
            get {
                return ResourceManager.GetString("DynManifestFilter_CheckIfErrorTimeControls_ItIsNotRecommendedToUseAGlobalFilterTo" +
                        "DoTimeTrimmingConsiderCreatingAnAssetFilterInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be lower than end time.
        /// </summary>
        internal static string DynManifestFilter_CheckIfErrorTimeControls_StartTimeMustBeLowerThanEndTime {
            get {
                return ResourceManager.GetString("DynManifestFilter_CheckIfErrorTimeControls_StartTimeMustBeLowerThanEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DVR Window must be at least 1 minute (or more).
        /// </summary>
        internal static string DynManifestFilter_CheckIfErrorTimeControls_TheDVRWindowMustBeAtLeast2MinutesOrMore {
            get {
                return ResourceManager.GetString("DynManifestFilter_CheckIfErrorTimeControls_TheDVRWindowMustBeAtLeast2MinutesOrMor" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset filter.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_AssetFilter {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_AssetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End timestamp.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_EndTimestamp {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_EndTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Quality Bitrate.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_FirstQualityBitrate {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_FirstQualityBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account filter.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_GlobalFilter {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_GlobalFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveBackoffDuration.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_LiveBackoffDuration {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_LiveBackoffDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PresentationWindowDuration.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_PresentationWindowDuration {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_PresentationWindowDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timestamp.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_StartTimestamp {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_StartTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timescale.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_Timescale {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_Timescale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track count.
        /// </summary>
        internal static string DynManifestFilter_DisplayFilterInfo_TrackCount {
            get {
                return ResourceManager.GetString("DynManifestFilter_DisplayFilterInfo_TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can take up to 2 minutes for streaming endpoint to refresh the rules.
        /// </summary>
        internal static string DynManifestFilter_DynManifestFilter_Load_ItCanTakeUpTo2MinutesForStreamingEndpointToRefreshTheRules {
            get {
                return ResourceManager.GetString("DynManifestFilter_DynManifestFilter_Load_ItCanTakeUpTo2MinutesForStreamingEndpoin" +
                        "tToRefreshTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import track filtering from :.
        /// </summary>
        internal static string DynManifestFilter_FillComboBoxImportFilters_ImportTrackFilteringFrom {
            get {
                return ResourceManager.GetString("DynManifestFilter_FillComboBoxImportFilters_ImportTrackFilteringFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a filter name.
        /// </summary>
        internal static string DynManifestFilter_textBoxFilterName_Validating_PleaseSpecifyAFilterName {
            get {
                return ResourceManager.GetString("DynManifestFilter_textBoxFilterName_Validating_PleaseSpecifyAFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value.
        /// </summary>
        internal static string DynManifestFilter_textBoxRawulong_Validating_IncorrectValue {
            get {
                return ResourceManager.GetString("DynManifestFilter_textBoxRawulong_Validating_IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string EditorXMLJSON_EditorXMLJSON_Close {
            get {
                return ResourceManager.GetString("EditorXMLJSON_EditorXMLJSON_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditorXMLJSON_EditorXMLJSON_Save {
            get {
                return ResourceManager.GetString("EditorXMLJSON_EditorXMLJSON_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from SAS Container Path.
        /// </summary>
        internal static string ImportHttp_ImportHttp_Load_ImportFromSASContainerPath {
            get {
                return ResourceManager.GetString("ImportHttp_ImportHttp_Load_ImportFromSASContainerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detected in the URL.
        /// </summary>
        internal static string ImportHttp_textBoxURL_TextChanged_ErrorDetectedInTheURL {
            get {
                return ResourceManager.GetString("ImportHttp_textBoxURL_TextChanged_ErrorDetectedInTheURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job report.
        /// </summary>
        internal static string JobInformation_DoJobStats_JobReport {
            get {
                return ResourceManager.GetString("JobInformation_DoJobStats_JobReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_Code {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detail.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_ErrorDetail {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_ErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input/output size.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_InputOutputSize {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_InputOutputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input size.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_InputSize {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_InputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Duration.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_JobDuration {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_JobDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output size.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_OutputSize {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_OutputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_Priority {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed size.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_ProcessedSize {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_ProcessedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_Task {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined, task did not finish or one of the assets has been deleted.
        /// </summary>
        internal static string JobInformation_JobInformation_Load_UndefinedTaskDidNotFinishOrOneOfTheAssetsHasBeenDeleted {
            get {
                return ResourceManager.GetString("JobInformation_JobInformation_Load_UndefinedTaskDidNotFinishOrOneOfTheAssetsHasBe" +
                        "enDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string JobInformation_listBoxTasks_SelectedIndexChanged_Body {
            get {
                return ResourceManager.GetString("JobInformation_listBoxTasks_SelectedIndexChanged_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string JobInformation_listBoxTasks_SelectedIndexChanged_Configuration {
            get {
                return ResourceManager.GetString("JobInformation_listBoxTasks_SelectedIndexChanged_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See clear value.
        /// </summary>
        internal static string JobInformation_listBoxTasks_SelectedIndexChanged_SeeClearValue {
            get {
                return ResourceManager.GetString("JobInformation_listBoxTasks_SelectedIndexChanged_SeeClearValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Events.
        /// </summary>
        internal static string LabelChannel {
            get {
                return ResourceManager.GetString("LabelChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Outputs.
        /// </summary>
        internal static string LabelProgram {
            get {
                return ResourceManager.GetString("LabelProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer &apos;{0}&apos; cancelled by user..
        /// </summary>
        internal static string Mainform_DoGridTransferDeclareCancelled_Transfer0CancelledByUser {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferDeclareCancelled_Transfer0CancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer &apos;{0}&apos; completed..
        /// </summary>
        internal static string Mainform_DoGridTransferDeclareCompleted_Transfer0Completed {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferDeclareCompleted_Transfer0Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer completed.
        /// </summary>
        internal static string Mainform_DoGridTransferDeclareCompleted_TransferCompleted {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferDeclareCompleted_TransferCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Mainform_DoGridTransferDeclareError_Error {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferDeclareError_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer &apos;{0}&apos;: Error.
        /// </summary>
        internal static string Mainform_DoGridTransferDeclareError_Transfer0Error {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferDeclareError_Transfer0Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer &apos;{0}&apos;: started.
        /// </summary>
        internal static string Mainform_DoGridTransferDeclareTransferStarted_Transfer0Started {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferDeclareTransferStarted_Transfer0Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Mainform_DoGridTransferInit_Destination {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferInit_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string Mainform_DoGridTransferInit_EndTime {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferInit_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress detail.
        /// </summary>
        internal static string Mainform_DoGridTransferInit_ProgressDetail {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferInit_ProgressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string Mainform_DoGridTransferInit_StartTime {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferInit_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit time.
        /// </summary>
        internal static string Mainform_DoGridTransferInit_SubmitTime {
            get {
                return ResourceManager.GetString("Mainform_DoGridTransferInit_SubmitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string TabAssets {
            get {
                return ResourceManager.GetString("TabAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account filters.
        /// </summary>
        internal static string TabFilters {
            get {
                return ResourceManager.GetString("TabFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms &amp; jobs.
        /// </summary>
        internal static string TabJobs {
            get {
                return ResourceManager.GetString("TabJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live events &amp; outputs.
        /// </summary>
        internal static string TabLive {
            get {
                return ResourceManager.GetString("TabLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming endpoints.
        /// </summary>
        internal static string TabOrigins {
            get {
                return ResourceManager.GetString("TabOrigins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string TabStorage {
            get {
                return ResourceManager.GetString("TabStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        internal static string TabTransfers {
            get {
                return ResourceManager.GetString("TabTransfers", resourceCulture);
            }
        }
    }
}
