//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMSExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutBox_AboutBox_About0 {
            get {
                return ResourceManager.GetString("AboutBox_AboutBox_About0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading credentials. Settings have been deleted..
        /// </summary>
        internal static string AMSLogin_AMSLogin_Load_ErrorReadingCredentialsSettingsHaveBeenDeleted {
            get {
                return ResourceManager.GetString("AMSLogin_AMSLogin_Load_ErrorReadingCredentialsSettingsHaveBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Global.
        /// </summary>
        internal static string AMSLogin_AzureGlobal {
            get {
                return ResourceManager.GetString("AMSLogin_AzureGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Government.
        /// </summary>
        internal static string AMSLogin_AzureGovernment {
            get {
                return ResourceManager.GetString("AMSLogin_AzureGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure in China.
        /// </summary>
        internal static string AMSLogin_AzureInChina {
            get {
                return ResourceManager.GetString("AMSLogin_AzureInChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to export all entries ? \n\nSelect &apos;Yes&apos; to export all, &apos;No&apos; to export the selection..
        /// </summary>
        internal static string AMSLogin_buttonExport_Click_DoYouWantToExportAllEntriesNNSelectYesToExportAllNoToExportTheSelection {
            get {
                return ResourceManager.GetString("AMSLogin_buttonExport_Click_DoYouWantToExportAllEntriesNNSelectYesToExportAllNoTo" +
                        "ExportTheSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AMSLogin_buttonExport_Click_Error {
            get {
                return ResourceManager.GetString("AMSLogin_buttonExport_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all entries.
        /// </summary>
        internal static string AMSLogin_buttonExport_Click_ExportAllEntries {
            get {
                return ResourceManager.GetString("AMSLogin_buttonExport_Click_ExportAllEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not recognized or incorrect..
        /// </summary>
        internal static string AMSLogin_buttonImportAll_Click_FileNotRecognizedOrIncorrect {
            get {
                return ResourceManager.GetString("AMSLogin_buttonImportAll_Click_FileNotRecognizedOrIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import and replace.
        /// </summary>
        internal static string AMSLogin_buttonImportAll_Click_ImportAndReplace {
            get {
                return ResourceManager.GetString("AMSLogin_buttonImportAll_Click_ImportAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are current entries in the list.\nDo you want replace them with the new ones or do a merge?\n\nSelect &apos;Yes&apos; to replace them, &apos;No&apos; to merge them..
        /// </summary>
        internal static string AMSLogin_buttonImportAll_Click_ThereAreCurrentEntriesInTheListNDoYouWantReplaceThemWithTheNewOnesOrDoAMergeNNSelectYesToReplaceThemNoToMergeThem {
            get {
                return ResourceManager.GetString("AMSLogin_buttonImportAll_Click_ThereAreCurrentEntriesInTheListNDoYouWantReplaceTh" +
                        "emWithTheNewOnesOrDoAMergeNNSelectYesToReplaceThemNoToMergeThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the credentials for {0} ?.
        /// </summary>
        internal static string AMSLogin_buttonLogin_Click_DoYouWantToSaveTheCredentialsFor0 {
            get {
                return ResourceManager.GetString("AMSLogin_buttonLogin_Click_DoYouWantToSaveTheCredentialsFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the credentials for {0} ?.
        /// </summary>
        internal static string AMSLogin_buttonLogin_Click_DoYouWantToUpdateTheCredentialsFor0 {
            get {
                return ResourceManager.GetString("AMSLogin_buttonLogin_Click_DoYouWantToUpdateTheCredentialsFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save credentials.
        /// </summary>
        internal static string AMSLogin_buttonLogin_Click_SaveCredentials {
            get {
                return ResourceManager.GetString("AMSLogin_buttonLogin_Click_SaveCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account name cannot be empty..
        /// </summary>
        internal static string AMSLogin_buttonSaveToList_Click_TheAccountNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("AMSLogin_buttonSaveToList_Click_TheAccountNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is mandatory.
        /// </summary>
        internal static string AMSLogin_CheckTextBox_ThisFieldIsMandatory {
            get {
                return ResourceManager.GetString("AMSLogin_CheckTextBox_ThisFieldIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad GUID format.
        /// </summary>
        internal static string AMSLogin_CheckTextBoxGuid_BadGUIDFormat {
            get {
                return ResourceManager.GetString("AMSLogin_CheckTextBoxGuid_BadGUIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update credentials.
        /// </summary>
        internal static string AMSLogin_listBoxAccounts_SelectedIndexChanged_UpdateCredentials {
            get {
                return ResourceManager.GetString("AMSLogin_listBoxAccounts_SelectedIndexChanged_UpdateCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}, {2} scale unit).
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_012ScaleUnit {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_012ScaleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}, {2} scale units).
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_012ScaleUnits {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_012ScaleUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetType.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_AssetType {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_AssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_Created {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Options.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_CreationOptions {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_CreationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;error, deleted?&gt;.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_ErrorDeleted {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_ErrorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsStreamable.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_IsStreamable {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_IsStreamable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_LastModified {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_Name {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent asset.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_ParentAsset {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_ParentAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent asset Id.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_ParentAssetId {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_ParentAssetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent asset(s).
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_ParentAssetS {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_ParentAssetS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Id.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_ProgramId {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_ProgramId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_State {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Account Byte used.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_StorageAccountByteUsed {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_StorageAccountByteUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Account Is Default.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_StorageAccountIsDefault {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_StorageAccountIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Account Name.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_StorageAccountName {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_StorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Url.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_StorageUrl {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_StorageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportsDynamicEncryption.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_SupportsDynamicEncryption {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_SupportsDynamicEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string AssetInformation_AssetInformation_Load_Type {
            get {
                return ResourceManager.GetString("AssetInformation_AssetInformation_Load_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string LabelChannel {
            get {
                return ResourceManager.GetString("LabelChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        internal static string LabelProgram {
            get {
                return ResourceManager.GetString("LabelProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string TabAssets {
            get {
                return ResourceManager.GetString("TabAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global filters.
        /// </summary>
        internal static string TabFilters {
            get {
                return ResourceManager.GetString("TabFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string TabJobs {
            get {
                return ResourceManager.GetString("TabJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string TabLive {
            get {
                return ResourceManager.GetString("TabLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string TabLog {
            get {
                return ResourceManager.GetString("TabLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming endpoints.
        /// </summary>
        internal static string TabOrigins {
            get {
                return ResourceManager.GetString("TabOrigins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processors.
        /// </summary>
        internal static string TabProcessors {
            get {
                return ResourceManager.GetString("TabProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string TabStorage {
            get {
                return ResourceManager.GetString("TabStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        internal static string TabTransfers {
            get {
                return ResourceManager.GetString("TabTransfers", resourceCulture);
            }
        }
    }
}
