//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSExplorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayAssetIDinGrid {
            get {
                return ((bool)(this["DisplayAssetIDinGrid"]));
            }
            set {
                this["DisplayAssetIDinGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useProtectedConfiguration {
            get {
                return ((bool)(this["useProtectedConfiguration"]));
            }
            set {
                this["useProtectedConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int NbItemsDisplayedInGrid {
            get {
                return ((int)(this["NbItemsDisplayedInGrid"]));
            }
            set {
                this["NbItemsDisplayedInGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRefresh {
            get {
                return ((bool)(this["AutoRefresh"]));
            }
            set {
                this["AutoRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AutoRefreshTime {
            get {
                return ((int)(this["AutoRefreshTime"]));
            }
            set {
                this["AutoRefreshTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:02")]
        public global::System.TimeSpan LiveKeyFrameInterval {
            get {
                return ((global::System.TimeSpan)(this["LiveKeyFrameInterval"]));
            }
            set {
                this["LiveKeyFrameInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public short LiveHLSFragmentsPerSegment {
            get {
                return ((short)(this["LiveHLSFragmentsPerSegment"]));
            }
            set {
                this["LiveHLSFragmentsPerSegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://amsplayer.azurewebsites.net/?player=flash&format=smooth&url={manifest url}" +
            "")]
        public string CustomPlayerUrl {
            get {
                return ((string)(this["CustomPlayerUrl"]));
            }
            set {
                this["CustomPlayerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomPlayerEnabled {
            get {
                return ((bool)(this["CustomPlayerEnabled"]));
            }
            set {
                this["CustomPlayerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("365")]
        public int DefaultLocatorDurationDays {
            get {
                return ((int)(this["DefaultLocatorDurationDays"]));
            }
            set {
                this["DefaultLocatorDurationDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayAssetStorageinGrid {
            get {
                return ((bool)(this["DisplayAssetStorageinGrid"]));
            }
            set {
                this["DisplayAssetStorageinGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PremiumWorkflowPresetXMLFilesCurrentFolder {
            get {
                return ((string)(this["PremiumWorkflowPresetXMLFilesCurrentFolder"]));
            }
            set {
                this["PremiumWorkflowPresetXMLFilesCurrentFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$")]
        public string Currency {
            get {
                return ((string)(this["Currency"]));
            }
            set {
                this["Currency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%programfiles32%\\ffmpeg\\bin")]
        public string ffmpegPath {
            get {
                return ((string)(this["ffmpegPath"]));
            }
            set {
                this["ffmpegPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%programfiles32%\\VideoLAN\\VLC")]
        public string VLCPath {
            get {
                return ((string)(this["VLCPath"]));
            }
            set {
                this["VLCPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microphone (High Definition Audio Device)")]
        public string DirectShowAudioDevice {
            get {
                return ((string)(this["DirectShowAudioDevice"]));
            }
            set {
                this["DirectShowAudioDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Webcam (High Definition Audio Device)")]
        public string DirectShowVideoDevice {
            get {
                return ((string)(this["DirectShowVideoDevice"]));
            }
            set {
                this["DirectShowVideoDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSlateCurrentFolder {
            get {
                return ((string)(this["DefaultSlateCurrentFolder"]));
            }
            set {
                this["DefaultSlateCurrentFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("myIssuer")]
        public string DynEncTokenIssuerv3 {
            get {
                return ((string)(this["DynEncTokenIssuerv3"]));
            }
            set {
                this["DynEncTokenIssuerv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("myAudience")]
        public string DynEncTokenAudiencev3 {
            get {
                return ((string)(this["DynEncTokenAudiencev3"]));
            }
            set {
                this["DynEncTokenAudiencev3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3650")]
        public int DefaultLocatorDurationDaysNew {
            get {
                return ((int)(this["DefaultLocatorDurationDaysNew"]));
            }
            set {
                this["DefaultLocatorDurationDaysNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeleteInstallationFile {
            get {
                return ((string)(this["DeleteInstallationFile"]));
            }
            set {
                this["DeleteInstallationFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SigniantFlightAPIKey {
            get {
                return ((string)(this["SigniantFlightAPIKey"]));
            }
            set {
                this["SigniantFlightAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayAssetAltIDinGrid {
            get {
                return ((bool)(this["DisplayAssetAltIDinGrid"]));
            }
            set {
                this["DisplayAssetAltIDinGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ConcurrentTransfers {
            get {
                return ((int)(this["ConcurrentTransfers"]));
            }
            set {
                this["ConcurrentTransfers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AssetAnalysisStart {
            get {
                return ((int)(this["AssetAnalysisStart"]));
            }
            set {
                this["AssetAnalysisStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AssetAnalysisStep {
            get {
                return ((int)(this["AssetAnalysisStep"]));
            }
            set {
                this["AssetAnalysisStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginListJSON {
            get {
                return ((string)(this["LoginListJSON"]));
            }
            set {
                this["LoginListJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputAssetsAdaptiveStreamingFormat {
            get {
                return ((bool)(this["OutputAssetsAdaptiveStreamingFormat"]));
            }
            set {
                this["OutputAssetsAdaptiveStreamingFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.015")]
        public decimal MESPricePerMin {
            get {
                return ((decimal)(this["MESPricePerMin"]));
            }
            set {
                this["MESPricePerMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideTaskbarNotifications {
            get {
                return ((bool)(this["HideTaskbarNotifications"]));
            }
            set {
                this["HideTaskbarNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginListRPv3JSON {
            get {
                return ((string)(this["LoginListRPv3JSON"]));
            }
            set {
                this["LoginListRPv3JSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int DefaultSASDurationInHours {
            get {
                return ((int)(this["DefaultSASDurationInHours"]));
            }
            set {
                this["DefaultSASDurationInHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DynEncTokenSymKeyv3 {
            get {
                return ((string)(this["DynEncTokenSymKeyv3"]));
            }
            set {
                this["DynEncTokenSymKeyv3"] = value;
            }
        }
    }
}
